name: clean_architecture_example
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  go_router: ^17.1.0
  riverpod: ^3.2.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
