name: feature_auth
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.8
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.8
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.4
  flutter:
    sdk: flutter
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
